# Generated by Django 3.1.7 on 2021-04-09 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('colonia', models.CharField(max_length=120)),
                ('d_tipo_asenta', models.CharField(max_length=120)),
                ('municipio', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('d_CP', models.CharField(max_length=120)),
                ('c_estado', models.CharField(max_length=120)),
                ('c_oficina', models.CharField(max_length=120)),
                ('c_CP', models.CharField(max_length=120)),
                ('c_tipo_asenta', models.CharField(max_length=120)),
                ('c_mnpio', models.CharField(max_length=120)),
                ('id_asenta_cpcons', models.CharField(max_length=120)),
                ('d_zona', models.CharField(max_length=120)),
                ('c_cve_ciudad', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Codigo postal',
                'verbose_name_plural': 'Codigos postales',
            },
        ),
    ]
